// Vue/my-app/src/App.vue
<template>
  <div id="app">
    <div
      v-for="(taskText, index) in taskList"
      class="flex"
      v-bind:key="index + 1"
    >
      <div>{{ index + 1 }}. {{ taskText }}</div>
      <input
        type="checkbox"
        v-bind:key="taskText"
        @change="handleChosenTask($event, taskText)"
      />
    </div>
    <div class="flex">
      <input ref="newTaskValue" />
      <button @click="addNewTask">Добавить</button>
    </div>
    <button @click="removeChosenTasks" :disabled="!chosenTasks.length">
      Удалить
    </button>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      taskList: [],
      chosenTasks: [],
    };
  },
  created() {
    fetch("https://kodaktor.ru/j/tasklist")
      .then((data) => data.json())
      .then((result) => (this.taskList = result.list));
  },
  methods: {
    addNewTask() {
      const newTaskValue = this.$refs.newTaskValue.value;
      console.log(newTaskValue, !newTaskValue);
      if (!this.taskList.includes(newTaskValue) && newTaskValue) {
        this.taskList = [...this.taskList, newTaskValue];
      }
    },
    removeChosenTasks() {
      const filteredTaskList = this.taskList.filter(
        (el) => !this.chosenTasks.includes(el)
      );
      this.taskList = [...filteredTaskList];
      this.chosenTasks = [];
    },
    handleChosenTask(e, taskText) {
      if (e.target.checked) {
        this.chosenTasks = [...this.chosenTasks, taskText];
      } else {
        const newChosenTasks = [...this.chosenTasks].filter(
          (el) => el !== taskText
        );
        this.chosenTasks = newChosenTasks;
      }
    },
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.flex {
  display: flex;
}
</style>

// React/my-app/src/App.js
import React, { useState, useEffect } from "react";
import "./App.css";

const App = () => {
  const [taskList, setTaskList] = useState([]);
  const [chosenTasks, setChosenTasks] = useState([]);
  const [newTaskValue, setNewTaskValue] = useState("");

  useEffect(() => {
    fetch("https://kodaktor.ru/j/tasklist")
      .then((data) => data.json())
      .then((result) => setTaskList(result.list));
  }, []);

  const addNewTask = () => {
    if (!taskList.includes(newTaskValue) && newTaskValue) {
      setTaskList([...taskList, newTaskValue]);
    }
  };

  const handleChosenTask = (taskText, e) => {
    if (e.target.checked) {
      setChosenTasks([...chosenTasks, taskText]);
    } else {
      const newChosenTasks = [...chosenTasks].filter((el) => el !== taskText);
      setChosenTasks(newChosenTasks);
    }
  };

  const removeChosenTasks = () => {
    const filteredTaskList = taskList.filter((el) => !chosenTasks.includes(el));
    setTaskList([...filteredTaskList]);
    setChosenTasks([]);
  };

  return (
    <div className="App">
      {taskList &&
        taskList.map((text, index) => {
          return (
            <div style={{ display: "flex" }} key={index + 1}>
              <div key={index + 1}>
                {index + 1}. {text}
              </div>
              <input
                key={text}
                type="checkbox"
                onChange={(e) => handleChosenTask(text, e)}
              />
            </div>
          );
        })}
      <div style={{ display: "flex" }}>
        <input
          value={newTaskValue}
          onChange={(e) => setNewTaskValue(e.target.value)}
        />
        <button onClick={addNewTask}>Добавить</button>
      </div>
      <button onClick={removeChosenTasks} disabled={!chosenTasks.length}>
        Удалить
      </button>
    </div>
  );
};

export default App;
